version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=telegram_super_secret_vps_key_999
    volumes:
      - ./chat.db:/app/chat.db
    restart: always
